server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/playground?serverTimeZone=Asia/Seoul
    username: sumin
    password: ENC(XcS0/NIaM+sz2geHTQ4imQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace
    com.smsoft.playgroundbe: info

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

