jasypt:
  encryptor:
    password: dummy

server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace
    com.smsoft.playgroundbe: debug

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ENC(U1EtXSpNel+7Kd8OERWvGGLeFhmI2uvtzha/3ZUaPwBUVxxytt4JfPO1fHxLlCgl)
    secret: ENC(S2Ss9axwa0AXkFWJK0T6J0sfR+c5+sRMD9GQ4s7a6NBOgLNEEOpIloY+RU8fZSyc)